# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.PositiveSmallIntegerField(max_length=2)),
                ('personell', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Footer Links',
            },
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Header Links',
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': 'Content Links'},
        ),
    ]
