# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20191208_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(max_length=250),
        ),
    ]
